name: Update README on Merge

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI manually
        run: |
          curl -fsSL -o gh.deb https://github.com/cli/cli/releases/download/v2.74.2/gh_2.74.2_linux_amd64.deb
          sudo dpkg -i gh.deb
          gh --version

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Get latest merged PR info
        id: pr_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_JSON=$(gh pr list --state merged --base master --limit 1 --json headRefName,number,files)
          echo "$PR_JSON" > pr.json
          echo "BRANCH_NAME=$(jq -r '.[0].headRefName' pr.json)" >> $GITHUB_ENV
          echo "PR_NUMBER=$(jq -r '.[0].number' pr.json)" >> $GITHUB_ENV
          jq -r '.[0].files[].path' pr.json > changed_files.txt

      - name: Update README.md
        run: |
          echo "## Merged Branch: $BRANCH_NAME" > update.md
          echo "" >> update.md
          echo "### Files Changed:" >> update.md
          REPO_URL="https://github.com/${{ github.repository }}/blob/master"

          while read file; do
            echo "- [$file]($REPO_URL/$file)" >> update.md
          done < changed_files.txt

          echo "" >> update.md
          cat README.md >> update.md
          mv update.md README.md

      - name: Commit and push README.md update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README after merging branch $BRANCH_NAME"
          git push
