name: Update README on Merge

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest merged PR
        id: pr
        run: |
          PR_JSON=$(gh pr list --state merged --base master --limit 1 --json headRefName,url,number)
          echo "PR_JSON=$PR_JSON" >> $GITHUB_ENV

      - name: Extract PR Info
        id: extract
        run: |
          echo "$PR_JSON" | jq -r '.[0].headRefName' > branch.txt
          echo "$PR_JSON" | jq -r '.[0].number' > pr_number.txt

          BRANCH=$(cat branch.txt)
          PR_NUMBER=$(cat pr_number.txt)

          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Get changed files
        id: changed
        run: |
          FILES=$(gh pr view ${{ steps.extract.outputs.pr_number }} --json files -q '.files[].path')
          echo "$FILES" > files.txt

      - name: Update README.md
        run: |
          echo "## Merged Branch: ${{ steps.extract.outputs.branch }}" > temp.md
          echo "" >> temp.md
          echo "### Files Changed:" >> temp.md

          REPO_URL="https://github.com/${{ github.repository }}/blob/master"

          while read file; do
            echo "- [$file]($REPO_URL/$file)" >> temp.md
          done < files.txt

          echo "" >> temp.md
          cat README.md >> temp.md
          mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with merged branch info"
          git push
