name: Update README on Merge

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch name and changed files
        id: extract
        run: |
          echo "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}" >> $GITHUB_OUTPUT

          FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update README.md
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          COMMIT_SHA="${{ github.sha }}"

          echo "### ${{ steps.extract.outputs.branch_name }}" >> README.md
          echo "" >> README.md
          echo "**Merged At:** $(date -u +"%Y-%m-%d %H:%M EEST")" >> README.md
          echo "**Changed Files:**" >> README.md

          while IFS= read -r file; do
            echo "  - [\`$file\`]($REPO_URL/blob/$COMMIT_SHA/$file)" >> README.md
          done <<< "${{ steps.extract.outputs.files }}"

      - name: Commit and push
        run: |
          git add README.md
          git commit -m "Update README with merged branch info [skip ci]" || echo "Nothing to commit"
          git push
